### ISSUE TITLE
Hinzufügen Möglich der Angabe der Buchung beim Übertragen der Personen

### ISSUE THREAD

**Issue by kleinbobi** [kleinbobi/IOSL_Zimmerverwaltung#12]
Da es möglich ist, Personen für eine Bereits bestehende Buchung einzutragen sollte die ID der Buchung mit den Personen Übertitelt werden (JSON).

**Comment by PaulPruenster** [comment]
Nicht nur Personen aber die ganze Buchung. Id ist bei neuen Buchungen null
